### ISSUE TITLE
CPU usage NaN or +Inf on Raspberry pi zero w on Arch linux

### ISSUE THREAD

**Issue by dfalis** [xxxserxxx/gotop#156]
##### gotop version:
gotop v4.0.0 (20200607T220720)
##### OS/Arch:
5.4.83-3-ARCH GNU/Linux
##### Terminal emulator: 
Windows terminal (ssh)
##### Any relevant hardware info:
Raspberry pi zero w (ARMv6)
##### tmux version:
none

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:
`error.log is empty`

I am using arch on Raspberry pi zero w and tried to install gotop with `yay -S gotop-bin` and `yay -S gotop-git`, but both were showing CPU usage on every process NaN or +Inf. Screenshot is from gotop-bin package. htop works normally.

![image](https://user-images.githubusercontent.com/38078336/105101968-13a09600-5aaf-11eb-9a7d-655651d89e0f.png)

**Comment by xxxserxxx** [comment]
This looks like a dupe of #135, which would have been fixed after v4.0.1. @dfalis, could you check with the current v4.1.0 release?

**Comment by dfalis** [comment]
##### gotop version:
gotop v4.1.0 (20210125T182433)

I still have the same issue.

![image](https://user-images.githubusercontent.com/38078336/105894110-359c9a00-6014-11eb-9018-92e9b8a0065d.png)

**Comment by lourkeur** [comment]
I encountered the same problem on Raspberry Pi 4, but upgrading to 4.1.1 fixed it.

##### gotop version:
`gotop v4.1.1 (Hadean)`
##### OS/Arch:
`4.19.118 GNU/Linux`
NixOS 20.09 aarch64
##### Terminal emulator: 
Sakura
##### Any relevant hardware info:
Raspberry Pi 4 8GB
##### tmux version:
Does not apply

No error.log

**Comment by dfalis** [comment]
Updated to version gotop v4.1.1 (20210203T222546) and now it works, closing issue.
