### ISSUE TITLE
Temperature for SSD is -273C

### ISSUE THREAD

**Issue by diced** [xxxserxxx/gotop#230]
##### gotop version:
`gotop v4.1.4.r0.gcd0cf0f (20220726T210256)` (from [`gotop-git` aur](https://aur.archlinux.org/packages/gotop-git))
##### OS/Arch:
Linux: `5.18.14-zen1-1-zen GNU/Linux`
##### Terminal emulator: 
Alacritty
##### Any relevant hardware info:
Recently installed a new NVMe SSD into my laptop, and the temperature readings are *very* inaccurate, with them saying they are around 300C or sometimes -300C. Upon closer inspection (viewing the logs at `~/.cache/gotop/errors.log`) it seems that it has trouble opening smart info for my drives. Something I found while looking into this is that sometimes when it updates, it seems to get the correct temperatures which are like around 20-30C but then in other cases when it updates it shows the -273C.

![image](https://user-images.githubusercontent.com/35403473/181159357-b05f473f-bb7d-46ad-a305-8cbb0626c2af.png)

```
21:03:48 remote.go:74: Remote: no remote URL provided; disabling extension
21:03:48 temp_nix.go:35: error opening smart info for nvme0n1: unknown drive type
21:03:48 temp_nix.go:35: error opening smart info for sda: unknown drive type
```

**Comment by rare-magma** [comment]
@diced this has been fixed already: https://github.com/xxxserxxx/gotop/pull/225
the fix is not present in the latest release

**Comment by anatol** [comment]
@diced is the problem fixed for you?

**Comment by diced** [comment]
> @diced is the problem fixed for you?

Nope, still happening on `gotop v4.2.0.r6.g7a8dcee (20221204T123821)` from the `gotop-git` AUR package.
